package Net::Async::Github::Branch;

use strict;
use warnings;

use parent qw(Net::Async::Github::Common);

=head1 NAME

Net::Async::Github::Branch

=head1 DESCRIPTION

Autogenerated module.

=cut

=head1 METHODS

=cut

=head2 name

Provides an accessor for C<name>.

=cut

sub name {
    shift->{name}
}

1;

