package Net::Async::Github::Commit;

use strict;
use warnings;

# VERSION

use parent qw(Net::Async::Github::Common);

=head1 NAME

Net::Async::Github::Commit

=head1 DESCRIPTION

Autogenerated module.

=cut

use URI::Template ();

=head1 METHODS

=cut

=head2 url

Provides an accessor for C<url>.

=cut

sub url {
    shift->{url}
}

=head2 sha

Provides an accessor for C<sha>.

=cut

sub sha {
    shift->{sha}
}

=head2 node_id

Provides an accessor for C<node_id>.

=cut

sub node_id {
    shift->{node_id}
}

=head2 html_url

Provides an accessor for C<html_url>.

=cut

sub html_url {
    $_[0]->{html_url} =
     URI::Template->new($_[0]->{html_url})
        unless ref $_[0]->{html_url};
    shift->{html_url}
}

=head2 comments_url

Provides an accessor for C<comments_url>.

=cut

sub comments_url {
    $_[0]->{comments_url} =
     URI::Template->new($_[0]->{comments_url})
        unless ref $_[0]->{comments_url};
    shift->{comments_url}
}

=head2 commit

Provides an accessor for C<commit>.

=cut

sub commit {
    shift->{commit}
}

=head2 parents

Provides an accessor for C<parents>.

=cut

sub parents {
    shift->{parents}
}

1;

